### ISSUE TITLE
External sync is broken

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#102]
Something is wrong with the external sync implementation on the `brains2` (imxrt) platform, and it was present before the firmware repositories were merged.
The main issue can be observed when connecting a cable to sync-in, waiting for a while, and removing it. The sequencer now tries to catch up and plays very quickly for some time.

**Comment by DavidMenting** [comment]
The issue is introduced in tempo.cpp
`  while (accum >= scaled_millis_per_beat) {
    accum -= scaled_millis_per_beat;
    handler._previous_clock_time = micros();
    handler.trigger();
  }`

after unplugging the sync plug `accum` will be way too large and this loop will trigger every time to get `accum` back in line

**Comment by DavidMenting** [comment]
I've split the unit testing framework to a separate issue: https://github.com/datomusic/duo-imxrt/issues/103

**Comment by ggVGc** [comment]
@DavidMenting I think this fix is more accurate: https://github.com/datomusic/duo-imxrt/pull/106

**Comment by ggVGc** [comment]
@DavidMenting Regarding the accumulator approach:
This is the best way that I know of to keep a steady rate of something based on time passed, since it cannot be known how frequently this function is called, and how regularly. It's the approach most commomly used the most for stable game loops that I've encountered and used, for example.
The accumulator is actually not constantly increasing, but rather used as a kind of cache to make sure we don't miss any elapsed time in the cases when the time since last call was either very short or longer than one beat.

This also means it's not really relevant for other tempo sources. The accumulator is used as a way to generate the correct amount of clock pulses based on CPU time, while for external sync we already get concrete clock pulses.
