### ISSUE TITLE
Drums do not work on Brains 2.0

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#109]
Pads do not trigger, and drum sounds are sometimes heard when the sequencer starts.
I have tracked the issue down to this commit: https://github.com/datomusic/duo-imxrt/pull/91/commits/1873b95146c3457d159711a2930a57c1b6e2bd56

I think we should revert it, and try to find a simpler fix for the LED issue. I can probably track down what happened while merging the repositories.

**Comment by DavidMenting** [comment]
Probably it's related to the move of drums.h into the boards directories, as Brains 2.0 and Brains 2.1 have drums that behave differently

**Comment by ggVGc** [comment]
No, I checked that actually. Reverting the commit mentioned in the description made it work again for me.
I'll try to have a look at fixing the LEDs without that change, by looking at the history of the repo merge and see where the error snuck in.
