### ISSUE TITLE
Some flickering occurs when clocked by USB MIDI

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#138]
At some tempos, and fairly infrequently, I see flickering of large parts of the sequencer panel when clocked over USB-MIDI.
Seems to be more common at higher tempos, and while playing.

**Comment by DavidMenting** [comment]
Solved forever! https://github.com/datomusic/duo-imxrt/commit/59be48bc7a1bfa9f62003f1ad804bdebc9d16993
