### ISSUE TITLE
Implement EEPROM interaction to store midi channel

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#39]
It is stubbed here: https://github.com/datomusic/arduino-rt1011/blob/0b091bb2e55eb91c969ba28ed8d8663420f8020a/src/duo-imxrt/stubs/arduino_stubs.h#L10

**Comment by DavidMenting** [comment]
We're moving to a separate EEPROM ic for DUO-Brains-2.1 and higher. I'm keeping this issue open to discuss development for that separate eeprom.
