### ISSUE TITLE
LEDs flicker slightly in some builds

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#49]
We still have flickering issues, and timings would become a lot better if we could use DMA.

Reference: https://ralimtek.com/posts/2021/ws2812/

**Comment by ggVGc** [comment]
This seems like a relevant reference implementation: https://github.com/pixelmatix/SmartMatrix/blob/52d56ad0a96896325e16948e741a46dde007e422/src/MatrixTeensy4Hub75Refresh_Impl.h#L400

From https://forum.pjrc.com/threads/66201-Teensy-4-1-How-to-start-using-FlexIO

**Comment by ggVGc** [comment]
Also relevant: https://www.nxp.com/docs/en/supporting-information/FTF-ACC-F1179_Introduction_to_FlexIO.pdf

**Comment by DavidMenting** [comment]
It might be that we are not putting pieces of code in the right spot. The iMX RT has a slightly complicated memory configuration in which some parts of memory can be cached and some can't. It is worth checking our linker script for overlapping locations and to see where stuff ends up.

https://community.nxp.com/t5/i-MX-RT-Knowledge-Base/Using-NonCached-Memory-on-i-MXRT/ta-p/1183369

**Comment by DavidMenting** [comment]
There is an implementation for writing WS2812 style leds with iMX RT Flexio written in Rust here: https://github.com/Finomnis/ws2812-flexio

We might be able to take inspiration from this.

**Comment by ggVGc** [comment]
Yeah, that's a great find. We might even be able to straight-up use that code. Building it into our binary shouldn't be that difficult, and I've already played around with bare-metal rust a bit in the past.

**Comment by DavidMenting** [comment]
Merged in https://github.com/datomusic/duo-imxrt/commit/59be48bc7a1bfa9f62003f1ad804bdebc9d16993
