### ISSUE TITLE
Unite and simplify repositories

### ISSUE THREAD

**Issue by ggVGc** [datomusic/duo-imxrt#86]
- Make old `duo-firmware` repo work with new branch
- When it works, move firmware to this repo, and make `duo-firmware` have the subrepo.

**Comment by DavidMenting** [comment]
This was finished in commit  https://github.com/datomusic/duo-imxrt/commit/2f7793ee0ea26903f10ddf17547200d2774ca65d

I propose we close this issue once we've verified that brains1 and brains2 builds are working 100% and once we've cleaned up stray files and branches

- [ ] brains1 build working
- [ ] brains2 build working
- [ ] clean up stray branches
- [ ] clean up stray files

**Comment by ggVGc** [comment]
Closing this in favour of https://github.com/datomusic/duo-imxrt/issues/150
