### ISSUE TITLE
update_firmware script can only be run from its own directory

### ISSUE THREAD

**Issue by DavidMenting** [datomusic/duo-imxrt#88]
When running the update_firmware script from outside its own directory, it fails mentioning it can't find /data/ivt_flashloader.bin

`Traceback (most recent call last):
  File "/Users/david/Development/duo-rt1011/duo-imxrt/src/../updater/update_firmware.py", line 127, in <module>
    main()
  File "/Users/david/Development/duo-rt1011/duo-imxrt/src/../updater/update_firmware.py", line 123, in main
    update_firmware(args.firmware_path, True)
  File "/Users/david/Development/duo-rt1011/duo-imxrt/src/../updater/update_firmware.py", line 72, in update_firmware
    flashloader_bytes = open("./data/ivt_flashloader.bin", "rb").read()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/ivt_flashloader.bin'`

So either we need a check to see whether the script is run from its own directory or it needs to be modified so that it can run from any location

**Comment by ggVGc** [comment]
This should be fixed by https://github.com/datomusic/duo-imxrt/pull/89

But, it was already possible to explicitly supply the path of the binary file with an option (although this might not be useful most of the time):
```
$ duo-imxrt/ python updater/update_firmware.py -h                                                                                                                                           |12:06:21 
usage: DUO firmware updater [-h] [-c] [firmware_path]

positional arguments:
  firmware_path

options:
  -h, --help        show this help message and exit
  -c, --continuous  Disable user interaction and keep polling after successful or failed updates.
```

**Comment by DavidMenting** [comment]
Works perfectly now! This is great for flashing the demo apps
